language: android
sudo: false
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $PWD/gradle-3.3/
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support
env:
  - ANDROID_HOME=/usr/local/android-sdk
before_script:
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install
script: "make travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
