language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-23
    - platform-tools
    - extra
env:
  - ANDROID_HOME=/usr/local/android-sdk
before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
    - unzip gradle-3.3-all.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install
script: "make travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
